# Generated by Django 4.2.2 on 2024-07-01 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='имя пользователя', max_length=150, verbose_name='name')),
                ('last_name', models.CharField(help_text='Фамилия пользователя', max_length=150, verbose_name='last_name')),
                ('surname', models.CharField(help_text='Отчество пользователя', max_length=150, verbose_name='surname')),
                ('contact_email', models.EmailField(help_text='email пользователя', max_length=254, unique=True, verbose_name='email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name', 'last_name', 'surname', 'contact_email'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetterOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send_date', models.DateTimeField(default=datetime.datetime(2024, 7, 1, 17, 22, 19, 431053), verbose_name='дата создания')),
                ('period', models.CharField(choices=[('once', 'Единожды'), ('every_day', 'Ежедневно'), ('every_week', 'Еженедельно'), ('every_month', 'Ежемесячно')], default='once', help_text='Периодичность', max_length=100, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена'), ('stopped', 'Остановлена')], default='created', help_text='Статус', max_length=100, verbose_name='Статус')),
                ('next_send_date', models.DateTimeField(default=datetime.datetime(2024, 7, 1, 17, 22, 19, 431053), verbose_name='дата следующей отправки')),
                ('last_send_date', models.DateTimeField(default=datetime.datetime(2024, 7, 1, 17, 22, 19, 431053), verbose_name='дата окончания отправки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['first_send_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='TrySend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_last_try', models.DateTimeField(auto_now=True, verbose_name='Последняя отправка')),
                ('status', models.CharField(max_length=1000, verbose_name='Статус')),
                ('server_answer', models.CharField(choices=[('success', 'Ошибка'), ('error', 'Успешно')], max_length=1000, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
