# Generated by Django 4.2.2 on 2024-07-01 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteroptions',
            name='first_send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 17, 51, 44, 343232), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='newsletteroptions',
            name='last_send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 17, 51, 44, 344232), verbose_name='дата окончания отправки'),
        ),
        migrations.AlterField(
            model_name='newsletteroptions',
            name='next_send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 17, 51, 44, 344232), verbose_name='дата следующей отправки'),
        ),
    ]
