# Generated by Django 4.2.2 on 2024-07-01 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0003_alter_newsletteroptions_first_send_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteroptions',
            name='first_send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 5, 22, 373044), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='newsletteroptions',
            name='last_send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 5, 22, 373044), verbose_name='дата окончания отправки'),
        ),
        migrations.AlterField(
            model_name='newsletteroptions',
            name='next_send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 5, 22, 373044), verbose_name='дата следующей отправки'),
        ),
    ]
