# Generated by Django 4.2.2 on 2024-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='Контент статьи')),
                ('photo', models.ImageField(upload_to='articles/photo')),
                ('view_counter', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('published_date', models.DateTimeField(auto_now=True, null=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
